import { Buffer } from 'node:buffer'
import { readFileSync, writeFileSync } from 'node:fs'

import { LAYOUTS, monorepo } from '../utils/project'
import {
  COMMAND,
  HEADER,
  hookLine,
  HUSKY_4_BANNER,
  HUSKY_4_RUNNER,
  notWritten,
  prepare,
  shownHook,
  syntaxCheck,
  written,
} from './utils'

const HOOK = '.git/hooks/pre-commit'

const EXITING_HOOKS = [
  {
    name: "git's pre-commit.sample",
    setup: '#!/bin/sh\n#\n# An example hook script to verify what is about to be committed.\n\n',
    commands: [
      'if git rev-parse --verify HEAD >/dev/null 2>&1',
      'then',
      '\tagainst=HEAD',
      'else',
      '\tagainst=$(git hash-object -t tree /dev/null)',
      'fi',
      '',
      'exec 1>&2',
      '',
      'exec git diff-index --check --cached $against --',
      '',
    ].join('\n'),
  },
  {
    name: 'the hook of the pre-commit framework',
    setup: [
      '#!/usr/bin/env bash',
      '# File generated by pre-commit: https://pre-commit.com',
      '# ID: 138fd403232d2ddd5efb44317e38bf03',
      '',
      '# start templated',
      'INSTALL_PYTHON=/usr/bin/python3',
      '',
    ].join('\n'),
    commands: [
      'ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)',
      '# end templated',
      '',
      'HERE="$(cd "$(dirname "$0")" && pwd)"',
      'ARGS+=(--hook-dir "$HERE" -- "$@")',
      '',
      'if [ -x "$INSTALL_PYTHON" ]; then',
      // oxlint-disable-next-line no-template-curly-in-string
      '    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"',
      'elif command -v pre-commit > /dev/null; then',
      // oxlint-disable-next-line no-template-curly-in-string
      '    exec pre-commit "${ARGS[@]}"',
      'else',
      "    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2",
      '    exit 1',
      'fi',
      '',
    ].join('\n'),
  },
]

describe.each(LAYOUTS)('prepare with an existing hook in a $name', ({ create, app }) => {
  const line = hookLine(app)
  const folder = app.slice(0, -1)
  const lineOfV003 = app === '' ? COMMAND : `cd "${folder}" && ${COMMAND}`

  async function prepareHook(hook: string) {
    const project = create().write({ [HOOK]: hook })

    const run = await prepare(project, [], { cwd: app })

    return { ...run, project, hook: project.read(HOOK) }
  }

  it('rewrites the line an older version wrote in place', async () => {
    const old =
      app === '' ? 'npx uncheck staged --fix' : `cd "${folder}" && yarn uncheck staged --fix`

    const { stdout, hook, project } = await prepareHook(`${HEADER}${old}\npnpm test\n`)

    expect(stdout).toBe(written(shownHook(project, app), 'updated'))
    expect(hook).toBe(`${HEADER}${line}\npnpm test\n`)
  })

  it.each(EXITING_HOOKS)(
    'moves the line v0.0.3 appended after the exec of $name before it',
    async ({ setup, commands }) => {
      const { stdout, hook, project } = await prepareHook(`${setup}${commands}${lineOfV003}\n`)

      expect(stdout).toBe(written(shownHook(project, app), 'updated'))
      expect(hook).toBe(`${setup}${line}\n${commands}`)

      const again = await prepare(project, [], { cwd: app })

      expect(again.stdout).toBe(written(shownHook(project, app), 'unchanged'))
    },
  )

  it('keeps in its block a line v0.0.3 rewrote in place', async () => {
    const block = (text: string) => `#!/bin/sh\nif [ -z "$SKIP_CHECKS" ]; then\n${text}\nfi\n`

    const { hook } = await prepareHook(block(lineOfV003))

    expect(hook).toBe(block(line))
  })

  it('keeps its line in each branch of an if, indented, so the hook still parses', async () => {
    const runs = (command: string) => (app === '' ? command : `(cd "${folder}" && ${command})`)
    const branches = (first: string, second: string) =>
      `#!/bin/sh\nif [ -n "$CI" ]; then\n  ${first}\nelse\n  ${second}\nfi\n`

    const { stdout, hook, project } = await prepareHook(
      branches(runs('pnpm exec uncheck staged --only=oxlint'), runs('pnpm exec uncheck staged')),
    )

    expect(stdout).toBe(written(shownHook(project, app), 'updated'))
    expect(hook).toBe(branches(line, line))
    expect(syntaxCheck(project.path(HOOK))).toEqual({ status: 0, stderr: '' })

    const again = await prepare(project, [], { cwd: app })

    expect(again.stdout).toBe(written(shownHook(project, app), 'unchanged'))
  })

  it.each([
    ['&&', 'pnpm test &&'],
    ['||', '[ -n "$SKIP_CHECKS" ] ||'],
    ['a backslash', 'git diff --cached --quiet || \\'],
  ])(
    'keeps in place the line of v0.0.3 after a command that runs on into it with %s',
    async (_, command) => {
      const existing = (text: string) => `#!/bin/sh\n${command}\n${text}\n`

      const { stdout, hook, project } = await prepareHook(existing(lineOfV003))

      expect(stdout).toBe(written(shownHook(project, app), 'updated'))
      expect(hook).toBe(existing(line))
      expect(syntaxCheck(project.path(HOOK))).toEqual({ status: 0, stderr: '' })

      const again = await prepare(project, [], { cwd: app })

      expect(again.stdout).toBe(written(shownHook(project, app), 'unchanged'))
    },
  )

  it.each([
    ['after a command that runs on into it', 'pnpm test &&\n\n', ''],
    ['that is all of an unindented block', 'if [ "$FULL" = 1 ]; then\n', 'fi\n'],
  ])('keeps in place a copy of its line %s', async (_, before, after) => {
    const existing = (text: string) => `${HEADER}${line}\n${before}${text}\n${after}`

    const { hook, project } = await prepareHook(existing(lineOfV003))

    expect(hook).toBe(existing(line))
    expect(syntaxCheck(project.path(HOOK))).toEqual({ status: 0, stderr: '' })
  })

  it('keeps its line after a block that runs it too', async () => {
    const runs = (command: string) => (app === '' ? command : `(cd "${folder}" && ${command})`)
    const existing = (inBlock: string, after: string) =>
      `#!/bin/sh\nif [ -n "$CI" ]; then\n  ${inBlock}\nfi\n${after}\n`

    const { stdout, hook, project } = await prepareHook(
      existing(runs('pnpm exec uncheck staged --only=oxlint'), `${runs(COMMAND)} || exit 1`),
    )

    expect(stdout).toBe(written(shownHook(project, app), 'updated'))
    expect(hook).toBe(existing(line, line))

    const again = await prepare(project, [], { cwd: app })

    expect(again.stdout).toBe(written(shownHook(project, app), 'unchanged'))
  })

  it('drops the copies of its line and settles on one', async () => {
    const copies = [
      line,
      app === '' ? 'uncheck staged' : `(cd "${folder}" && npx --no uncheck staged)`,
      app === '' ? 'bunx uncheck staged --only=oxfmt' : `cd "${folder}" && bunx uncheck staged`,
    ]

    const { stdout, hook, project } = await prepareHook(
      `${HEADER}${copies.join('\npnpm test\n')}\n`,
    )

    expect(stdout).toBe(written(shownHook(project, app), 'updated'))
    expect(hook).toBe(`${HEADER}${line}\npnpm test\npnpm test\n`)

    const again = await prepare(project, [], { cwd: app })

    expect(again.stdout).toBe(written(shownHook(project, app), 'unchanged'))
  })

  it('leaves alone the lines that only mention the command or run it another way', async () => {
    const others = [
      'echo "runs uncheck staged"',
      'npx uncheck staged --only=oxfmt && pnpm test',
      'pnpm exec uncheck staged --fix || echo "not blocking"',
      'pnpm exec uncheck staged src/index.ts',
      'pnpm exec uncheck stagedly',
      'pnpm dlx uncheck staged',
    ]

    const { hook } = await prepareHook(`#!/bin/sh\n${others.join('\n')}\n`)

    expect(hook).toBe(`#!/bin/sh\n${line}\n${others.join('\n')}\n`)
  })

  it('runs before the commands of the hook and after its setup', async () => {
    const setup = [
      '#!/usr/bin/env bash',
      '# lint before committing',
      '',
      'set -e',
      'unset GIT_INDEX_FILE',
      'export HOOKS="$(dirname "$0")"',
      'source ~/.profile',
      '. "$HOOKS/env"',
      '\\. "$HOOKS/nvm.sh"',
      '[ -f "$HOOKS/local" ] && . "$HOOKS/local"',
      'test -s "$HOOKS/path" && source "$HOOKS/path"',
      'NODE_OPTIONS=--max-old-space-size=4096',
    ].join('\n')
    const commands = 'export CI=1 && exec pnpm lint-staged\npnpm test\n'

    const { hook } = await prepareHook(`${setup}\n${commands}`)

    expect(hook).toBe(`${setup}\n${line}\n${commands}`)
  })

  it('runs after the setup of husky 8, whose script runs the hook again', async () => {
    const setup = '#!/usr/bin/env sh\n. "$(dirname -- "$0")/_/husky.sh"\n\n'

    const { hook } = await prepareHook(`${setup}npx lint-staged\n`)

    expect(hook).toBe(`${setup}${line}\nnpx lint-staged\n`)
  })

  it.each([
    ['escaped double quotes', 'export A="\\"" && exec lint B="\\""'],
    ['double quotes between single quotes', "export A='\"' && exec lint B='\"'"],
  ])('runs before an export that goes on to run a command, with %s', async (_, command) => {
    const { hook } = await prepareHook(`#!/bin/sh\n${command}\n`)

    expect(hook).toBe(`#!/bin/sh\n${line}\n${command}\n`)
  })

  it('runs after the lines of nvm that set up its PATH, whose quotes hold commands', async () => {
    const setup = [
      '#!/bin/sh',
      // oxlint-disable-next-line no-template-curly-in-string
      'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"',
      '[ -s "$NVM_DIR/nvm.sh" ] && \\. "$NVM_DIR/nvm.sh"',
    ].join('\n')

    const { hook } = await prepareHook(`${setup}\nnpx lint-staged\n`)

    expect(hook).toBe(`${setup}\n${line}\nnpx lint-staged\n`)
  })

  it('runs before the runner of husky 4, which always exits', async () => {
    const { hook } = await prepareHook(`${HUSKY_4_BANNER}${HUSKY_4_RUNNER}\n`)

    expect(hook).toBe(`${HUSKY_4_BANNER}${line}\n${HUSKY_4_RUNNER}\n`)
  })

  it('moves the line an older version wrote after the runner of husky 4 before it', async () => {
    const old = app === '' ? line : `(cd "${folder}" && ${COMMAND}) || exit 1`

    const { stdout, hook, project } = await prepareHook(
      `${HUSKY_4_BANNER}${HUSKY_4_RUNNER}\n${old}\n`,
    )

    expect(stdout).toBe(written(shownHook(project, app), 'updated'))
    expect(hook).toBe(`${HUSKY_4_BANNER}${line}\n${HUSKY_4_RUNNER}\n`)

    const again = await prepare(project, [], { cwd: app })

    expect(again.stdout).toBe(written(shownHook(project, app), 'unchanged'))
  })

  it('keeps its line after a block that only runs the husky 4 runner when it exists', async () => {
    const existing = `#!/bin/sh\nif [ -f "$(dirname "$0")/husky.sh" ]; then\n  ${HUSKY_4_RUNNER}\nfi\n${line}\n`

    const { stdout, hook, project } = await prepareHook(existing)

    expect(stdout).toBe(written(shownHook(project, app), 'unchanged'))
    expect(hook).toBe(existing)
  })

  it.each([
    ['a trailing backslash', 'export PATH=/opt/bin:\\\n/usr/bin:$PATH\n'],
    ['an open double quote', 'MESSAGE="checks\n. before committing"\n'],
    ['an open single quote', "MESSAGE='checks\n. before committing'\n"],
    ['an open command substitution', 'FILES=$(\n  git diff --cached --name-only\n)\n'],
    [
      'a here-document in a command substitution',
      'export MESSAGE=$(cat <<EOF\nchecks before committing\nEOF\n)\n',
    ],
    ['an open backtick', 'FILES=`\n  git diff --cached --name-only\n`\n'],
  ])('runs before a setup line continued by %s', async (_, setup) => {
    const { hook } = await prepareHook(`#!/bin/sh\n${setup}npx lint-staged\n`)

    expect(hook).toBe(`#!/bin/sh\n${line}\n${setup}npx lint-staged\n`)
  })

  it.each([
    [
      'an apostrophe in a trailing comment',
      'export PATH="/opt/bin:$PATH"  # GUI clients don\'t load ~/.zshrc',
    ],
    ['an apostrophe between double quotes', 'export MESSAGE="don\'t commit secrets"'],
    ['a trailing comment after a variable', 'PATH="/opt/homebrew/bin:$PATH" # for GUI clients'],
    ['a semicolon in a trailing comment', 'export PATH="/opt/bin:$PATH" # GUI clients; see docs'],
  ])('runs after a setup line with %s', async (_, setup) => {
    const { hook } = await prepareHook(`#!/bin/sh\n${setup}\nnpx lint-staged\n`)

    expect(hook).toBe(`#!/bin/sh\n${setup}\n${line}\nnpx lint-staged\n`)
  })

  it.each([
    ['an odd single quote', "# don't commit secrets"],
    ['an odd double quote', '# the "main branch'],
    ['a trailing backslash', '# see C:\\'],
  ])('runs after a setup comment with %s, which continues nothing', async (_, comment) => {
    const { hook } = await prepareHook(`#!/bin/sh\n${comment}\nnpx lint-staged\n`)

    expect(hook).toBe(`#!/bin/sh\n${comment}\n${line}\nnpx lint-staged\n`)
  })

  it('goes at the end of a hook that only sets up', async () => {
    const { hook } = await prepareHook('#!/bin/sh\n# nothing yet\n')

    expect(hook).toBe(`#!/bin/sh\n# nothing yet\n${line}\n`)
  })

  it('ends a hook without a trailing newline before adding its line', async () => {
    const { hook } = await prepareHook('#!/bin/sh\n# nothing yet')

    expect(hook).toBe(`#!/bin/sh\n# nothing yet\n${line}\n`)
  })

  it('keeps a hook without a trailing newline as it is around its line', async () => {
    const { hook } = await prepareHook('#!/bin/sh\necho "checking"')

    expect(hook).toBe(`#!/bin/sh\n${line}\necho "checking"`)
  })

  it('fills an empty hook with its line alone', async () => {
    const { stdout, hook, project } = await prepareHook('')

    expect(stdout).toBe(written(shownHook(project, app), 'updated'))
    expect(hook).toBe(`${line}\n`)
    expect(project.mode(HOOK)).toBe(0o755)
  })

  it('leaves a hook in another language alone and says what it should run', async () => {
    const script = '#!/usr/bin/env python3\nprint("checked")\n'

    const { exitCode, stdout, hook, project } = await prepareHook(script)

    expect(exitCode).toBe(0)
    expect(stdout).toBe(
      notWritten(
        shownHook(project, app),
        `it is not a shell script, have it run \`${line}\` yourself`,
      ),
    )
    expect(hook).toBe(script)
  })

  it.each([
    ['invalid UTF-8', Buffer.from([0x7f, 0x45, 0x4c, 0x46, 0x02, 0xff, 0xfe])],
    ['a NUL byte', Buffer.from('#!/bin/sh\necho "\0"\n')],
  ])('leaves a hook with %s alone', async (_, bytes) => {
    const project = create()
    writeFileSync(project.path(HOOK), bytes)

    const { stdout } = await prepare(project, [], { cwd: app })

    expect(stdout).toBe(
      notWritten(
        shownHook(project, app),
        `it is not a shell script, have it run \`${line}\` yourself`,
      ),
    )
    expect(readFileSync(project.path(HOOK))).toEqual(bytes)
  })
})

describe('prepare with an existing hook in a monorepo', () => {
  it('puts the line of a new package after the lines of the others', async () => {
    const root = hookLine('')
    const core = hookLine('packages/core/', `${COMMAND} --only=oxlint`)
    const project = monorepo().write({
      [HOOK]: `#!/bin/sh\nexport CI=1\n${root}\n${core}\npnpm test\n`,
    })

    await prepare(project, [], { cwd: 'packages/app' })

    expect(project.read(HOOK)).toBe(
      `#!/bin/sh\nexport CI=1\n${root}\n${core}\n${hookLine('packages/app/')}\npnpm test\n`,
    )
  })

  it('rewrites the lines the previous version wrote in place, then leaves them unchanged', async () => {
    const project = monorepo().write({
      [HOOK]: [
        '#!/bin/sh',
        '(cd "packages/core" && pnpm exec uncheck staged --fix --only=oxlint) || exit 1',
        '(cd "packages/app" && pnpm exec uncheck staged --fix) || exit 1',
        'pnpm test',
        '',
      ].join('\n'),
    })

    const { stdout } = await prepare(project, [], { cwd: 'packages/app' })

    expect(stdout).toBe(written(project.path(HOOK), 'updated'))
    expect(project.read(HOOK)).toBe(
      [
        '#!/bin/sh',
        hookLine('packages/core/', `${COMMAND} --only=oxlint`),
        hookLine('packages/app/'),
        'pnpm test',
        '',
      ].join('\n'),
    )

    const again = await prepare(project, [], { cwd: 'packages/app' })

    expect(again.stdout).toBe(written(project.path(HOOK), 'unchanged'))
  })

  it('moves the lines of the other packages after the runner of husky 4 before it', async () => {
    const core = hookLine('packages/core/')
    const project = monorepo().write({
      [HOOK]: `${HUSKY_4_BANNER}${HUSKY_4_RUNNER}\n${core}\n`,
    })

    await prepare(project)

    expect(project.read(HOOK)).toBe(
      `${HUSKY_4_BANNER}${core}\n${hookLine('')}\n${HUSKY_4_RUNNER}\n`,
    )
  })

  it('leaves alone the lines that enter a package with --cwd and adds its own', async () => {
    const lines = [
      `${COMMAND} --cwd=packages/core || exit 1`,
      `${COMMAND} --only=oxlint --cwd=packages/app || exit 1`,
    ]
    const project = monorepo().write({ [HOOK]: `#!/bin/sh\n${lines.join('\n')}\n` })

    const { stdout } = await prepare(project)

    expect(stdout).toBe(written(HOOK, 'updated'))
    expect(project.read(HOOK)).toBe(`#!/bin/sh\n${hookLine('')}\n${lines.join('\n')}\n`)

    const again = await prepare(project)

    expect(again.stdout).toBe(written(HOOK, 'unchanged'))
  })

  it('puts the line of a new package before a block that runs the line of another', async () => {
    const block = `if [ -z "$QUICK" ]; then\n  ${hookLine('packages/core/')}\nfi\n`
    const project = monorepo().write({ [HOOK]: `#!/bin/sh\n${block}` })

    await prepare(project)

    expect(project.read(HOOK)).toBe(`#!/bin/sh\n${hookLine('')}\n${block}`)
  })

  it('moves up the lines v0.0.3 appended for the other packages, in order, and rewrites them', async () => {
    const project = monorepo().write({
      [HOOK]: [
        '#!/bin/sh',
        'pnpm exec uncheck staged --fix',
        'pnpm test',
        'cd "packages/core" && pnpm exec uncheck staged --fix --only=oxlint',
        'cd "packages/app" && pnpm exec uncheck staged --fix',
        '',
      ].join('\n'),
    })

    const { stdout } = await prepare(project, ['--no-fix'], { cwd: 'packages/app' })

    expect(stdout).toBe(written(project.path(HOOK), 'updated', 'pnpm exec uncheck staged'))
    expect(project.read(HOOK)).toBe(
      [
        '#!/bin/sh',
        'git --literal-pathspecs diff --cached --quiet -- "packages/core" || [ ! -d "packages/core" ] || (cd "packages/core" && pnpm exec uncheck staged --fix --only=oxlint) || exit 1',
        'git --literal-pathspecs diff --cached --quiet -- "packages/app" || [ ! -d "packages/app" ] || (cd "packages/app" && pnpm exec uncheck staged) || exit 1',
        'pnpm exec uncheck staged --fix || exit 1',
        'pnpm test',
        '',
      ].join('\n'),
    )

    const again = await prepare(project, ['--no-fix'], { cwd: 'packages/app' })

    expect(again.stdout).toBe(written(project.path(HOOK), 'unchanged', 'pnpm exec uncheck staged'))
  })
})
